---
- hosts: localhost
  connection: local
  become: yes
  remote_user: "{{ ansible_facts['user_id'] }}"
  
  roles:
      - default
      - role: crosvm
        when: crosvm is defined or all is defined
      - role: docker
        when: docker is defined or all is defined
      - role: go
        when: go is defined or all is defined
      - role: vscode
        when: vscode is defined or all is defined

