- hosts: localhost
  become: true

  tasks:
#   - include: tasks/packages.yml
    - name: Update all packages
      apt:
        update_cache: yes
        upgrade: dist
    - name: Install Packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common