---
# tasks file for go

- name: Get the url for the latest golang version
  shell: wget -qO- https://golang.org/dl/ | grep -oP 'https:\/\/dl\.google\.com\/go\/go([0-9\.]+)\.linux-amd64\.tar\.gz' | head -n 1
  args:
    warn: no
  register: go_url

- debug:
    var: go_url
    verbosity: 2
    
  # set_fact:
  #   go_u={{ go_url.stdout }}

# - name: Get the url for the sha256
#   set_fact:
#     go_256="{{ go_url.stdout }}.sha256"

- name: Determine latest version of go
  shell: "{{ go_url.stdout }} | grep -oP 'go[0-9\\.]+' | grep -oP '[0-9\\.]+' | head -c -2"
  register: go_latest
  # set_fact:
  #   go_latest_version={{ go_latest.stdout }}

- name: Determine current version of go
  shell: go version | cut -d" " -f3 | sed -e's/go//g'
  register: go_version
  # set_fact:
  #   go_ver={{ go_version.stdout }}

- name: Download file with checksum url (sha256)
  get_url:
    url: "{{ go_url.stdout }}"
    dest: /tmp/
    checksum: "sha256:{{ go_url.stdout }}.sha256"
  when: go_version.stdout != go_latest.stdout

- name: Remove old version if needed
  file: 
    state: absent
    path: /usr/local/go
  register: no_go

# - name: Install new version if no current version or if newer version

# - name: Set GOPATH etc

# - name: Check installed version is current